version: '3.8'

services:
  reserve-ex-app:
    build:
      context: .
      dockerfile: ./reserve-ex-app/Dockerfile
    image: 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api
    container_name: reserve-ex-app
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge