spring:
  application:
    name: reserve-ex-app

server:
  port: 8081

---
spring:
  config:
   activate:
    on-profile: local

server:
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: dev