name: Dockerizing to Amazon ECR

on:
  push:       # 트리거
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Docker build 및 ECR로 푸시
        docker compose build
        docker tag 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api:latest 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api:${GITHUB_SHA}
        docker push 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api:${GITHUB_SHA}

    - name: Get version
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"
    
    # kustomize 명령을 가져온다.
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        # Kubernetes 설정정보 저장소
        repository: ReServeMarket/reserve-gitops
        ref: main
        # 다른 저장소에 push 하려면 Personal Access Token이 필요.
        token: ${{ secrets.ACTION_TOKEN }}
        path: reserve-gitops

    # 새 이미지 버전으로 파일 수정
    - name: Update Kubernetes resources
      run: |
        cd reserve-gitops/charts/reserve-api/
        ls
        sed -i "s|tag:.*|tag: ${GITHUB_SHA}|" values.yaml
        cat values.yaml
        
    # 수정된 파일 commit & push
    - name: Commit files
      run: |
        git add .
        git config --global user.email "xxxlsu@naver.com"
        git config --global user.name "igyeong-yun"
        git commit -am "Update image tag to ${{ github.sha }}"
        git push origin main
